extends: existence
message: "Legacy cross-reference syntax: '%s'. Use the current AsciiDoc xref style."
level: warning
scope: text

tokens:
  # e.g., old-style AsciiDoc double-angle links
  - '<<[^>]+>>'
