extends: spelling

message: "Did you really mean '%s'?"
level: error

# Tell Vale where the Hunspell dictionaries live on the system
dicpath: /usr/share/hunspell

# Which dictionary to use (expects en_GB.aff and en_GB.dic)
dictionaries:
  - en_GB
