[[preface]]
# Preface


## placeholder text
The differences between a foreword, a preface and an introduction:

https://greenleafbookgroup.com/learning-center/book-creation/distinguishing-between-a-foreword-a-preface-and-an-introduction[DISTINGUISHING BETWEEN A FOREWORD, A PREFACE, AND AN INTRODUCTION]

* A foreword is written by someone other than the author and tells the readers why they should read the book.
* A preface is written by the author and tells readers how and why the book came into being.
* An introduction introduces readers to the main topics of the manuscript and prepares readers for what they can expect.

They are added to the book in this order.

## Date started

somewhere in 2013


[[contributors]]
## Contributors
obviously Bart and me but also Steve for the podcast logo, suggesting we make it a standalone show, and doing all of the editing to make it so
Helma for making the book a reality

For true programmer's nerdery, the contributors according to git:

----
include::contributors.txt[]
----


## Ongoing - expect updates e.g. zsh is the bomb now

[[zsh]]
## zsh warning - Maybe in an Intro vs. a Forward?

Since Catalina, the default shell is no longer Bash, but zsh. If you want to follow along with the tutorial, switch to a Bash shell by entering the following command:

[source,shell]
----
bash --login
----

You will see a warning:

[source,shell]
----
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
----
