[[troubleshooting]]
= ePub Troubleshooting tips

If you open this ePub in Apple Books, you might encounter these problems.
Here are instructions on how to solve them.

== Audio files in Apple Books

If you open the ePub version of this book in Books on an iPad or iPhone you might run into the problem that the episodes cannot be played. When you press the play button it takes some time and then shows the word 'Error'.

You can solve this problem by following these actions:

* Go to the iOS/iPadOS home screen
* Open menu:Settings[Books]
* Toggle 'Online Content' to *off*
* In Books, go back to the library
* Remove the downloaded book, just the download, no need to remove the book from iCloud
* Switch back to Settings
* Toggle the 'Online Content' to *on*
* Open Books
* Select the Taming the Terminal Book in your library to redownload
* You should now get a message to confirm that you want *allow Apple Books to access the publisher's online content for this book?*
* Select Allow

The audio files should now play and not give an error.
In some cases it make take some time for the audio files to be available.

== No cover in Apple Books

If your ebook has no cover image in Apple Books on your iPad or iPhone, just the standard generated coloured background with only the title and the author's name in white, then you've probably added the ebook to Apple Books on your Mac and you're suffering from a long standing bug in Apple Books.

You can solve this problem by following these actions.

* Remove the ebook from the library. Select *Delete everywhere*
* Airdrop the ebook from your Mac to your iPad
* or add the ebook to a folder that you can sync with your iPad outside of Books. This can be a folder in iCloud Drive or Dropbox or any cloudbased storage that is linked to both your computer and your iPad.
* On the iPad you will get a message that asks you to select the application you want to open the Taming the Terminal Book in.
* Select *Books*
* You will now see the ebook with its cover in the library
* You can now delete the file from your cloudbased storage as syncing will be taken care of by Books.

This also works on the iPhone.
