[[introduction]]
= Introduction
include::variables.adoc[]

Taming the Terminal is specifically targeted at learning the macOS Terminal but most of the content is applicable to the Linux command line. If you're on Windows, it is recommended that you use the Linux Subsystem for Windows to learn along with this book. Wherever practical, Bart explains the differences that you may encounter if you're not on macOS.

The series started in April 2013 and was essentially complete in 2015 after 35 of n lessons, but Bart carefully labeled them as "of n" because he knew that over time there likely would be new episodes.  More episodes have indeed come out, and this book will be updated over time as the new instalments are released.

== Zsh vs Bash
In macOS Catalina, released after much of the tutorial content in this book was released, Apple replaced the default shell bash with the zsh shell. As a result you'll notice the prompt change from `$` to `%` partway through the book.  There may be cases where the instructions given during the bash days might not work with today's zsh.

To switch back to bash if you do run into problems, simply enter:

[source,shell]
----
bash --login
----

You'll be shown this warning explaining how to switch your default interactive shell back to zsh, and can proceed with the lessons.

[source,shell]
----
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
----

If you'd like to see these instalments in their web form, you can go to https://ttt.bartificer.net[ttt.bartificer.net].

If you enjoy the format of this series, you might also enjoy the podcast and written tutorials for Bart and Allison's next series, Programming By Stealth at https://pbs.bartificer.net[pbs.bartificer.net].

Feedback on the book can be sent to allison@podfeet.com.

We hope you enjoy your journey with Taming the Terminal.

== Full Disk Access
Starting with macOS 10.14 Mojave, Apple added privacy controls that prevent apps from accessing your entire disk without explicit permission. This series assumes the Terminal app has been granted either _Files and Folders_ or _Full Disk Access_ permission under _Privacy & Security_ in the macOS settings.