[[preface]]
# Preface
Taming the Terminal was created as a podcast and written tutorial with Bart Busschots as the instructor and Allison Sheridan as the student.  Taming the Terminal started its life as part of the https://www.podfeet.com[NosillaCast Apple Podcast] and was eventually spun off as a standalone Podcast. Bart and Allison have been podcasting together for many years, and their friendship and camaraderie make the recordings a delightful way to learn these technical concepts.

The book version of the podcast was a labor of love by Allison Sheridan and Helma van der Linden as a surprise gift to Bart Busschots for all he has done for the community.

## Introduction
Taming the Terminal is specifically targeted at learning the macOS Terminal but most of the content is applicable to the Linux command line. If you're on Windows, it is recommended that you use the Linux Subsystem for Windows to learn along with this book. Wherever practical, Bart explains the differences that you may encounter if you're not on macOS.

The series was essentially complete in 2015 after 35 of n lessons, but Bart carefully labeled them as "of n" because he knew that over time there likely would be new episodes.  More episodes have indeed come out, and this book will be updated over time as the new instalments are released. 

### Zsh vs Bash
In macOS Catalina, released after much of the tutorial content in this book was released, Apple replaced the default shell bash with the zsh shell. As a result you'll notice the prompt change from `$` to `%` partway through the book.  There may be cases where the instructions given during the bash days might not work with today's zsh. 

To switch back to bash if you do run into problems, simply enter:

[source,shell]
----
bash --login
----

 You'll be shown this warning explaining how to switch your default interactive shell back to zsh, and can proceed with the lessons. 

[source,shell]
----
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
----

If you'd like to see these instalments in their web form, you can go to https://ttt.bartificer.net[ttt.bartificer.net].

If you enjoy the format of this series, you might also enjoy the podcast and written tutorials for Bart and Allison's next series, Programming By Stealth at https://pbs.bartificer.net[pbs.bartificer.net].

Feedback on the book can be sent to allison@podfeet.com.

We hope you enjoy your journey with Taming the Terminal.


----
