[[troubleshooting]]
= ePub Troubleshooting tips

If you open this ePub in Apple Books, you might encounter these problems.
Here are instructions on how to solve them.

== Audio files in Apple Books

If you open the ePub version of this book in Books on an iPad or iPhone you might run into the problem that the episodes cannot be played. When you press the play button it takes some time and then shows the word 'Error'.

You can solve this problem by following these actions:

* go back to the home screen
* go to menu:Settings[Books]
* toggle 'Online Content' to off
* in Books, go back to the library
* remove the downloaded book, just the download, no need to remove the book from iCloud
* switch to Settings
* toggle the 'Online Content' to on
* open Books
* open this ebook
* you now get a message to confirm that you want *allow Apple Books to access the publisher's online content for this book?*
* tap Allow
The audio files should now play and not give an error.

== No cover in Apple Books

If your ebook has no cover image in Apple Books on your iPad or iPhone, just the standard generated coloured background with only the title and the author's name in white, then you've probably added the ebook to Apple Books on your Mac and you're suffering from a long standing bug in Apple Books.

You can solve this problem by following these actions.

* remove the ebook from the library. Select *Delete everywhere*.
* add the ebook to a folder that you can sync with your iPad outside of Books. This can be a folder in iCloud Drive or Dropbox or any cloudbased storage that is linked to both your computer and your iPad.
* or Airdrop the ebook from your Mac to your iPad.
* on the iPad you will get a message that asks you to select the application you want to open the ebook in.
* Select Books.
* you will now see the ebook with its cover in the library.

This also works on the iPhone.
